config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  root to: 'pages#home'
  resources :chatrooms, only: [:index, :show, :create] do
    resources :messages, only: :create
  end
  resources :item_designs, only: [:show, :index]
  resources :secured_items, only: [:new, :edit, :create, :update]
  get 'search', to: 'item_designs#index', as: :search
  get 'profile', to: 'pages#profile'
  patch 'secured_items/:id/activate', to: 'secured_items#activate', as: :activate
  patch 'secured_items/:id/deactivate', to: 'secured_items#deactivate', as: :deactivate
end

app/models/item_design.rb
class ItemDesign < ApplicationRecord
  has_one_attached :design
  has_many :secured_items
  has_many :subscriptions
  monetize :refund_cents

end

app/controllers/item_designs_controller.rb
class ItemDesignsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def show
    @item_design = ItemDesign.find(params[:id])
    @secured_item = SecuredItem.new
    @secured_item.item_design = @item_design
    @subscriptions = Subscription.where(item_design: @item_design)
  end

  def index
    if params[:search].present?
      items_query = "name ILIKE :search OR item_type ILIKE :search"
      @items = ItemDesign.where(items_query, search: "%#{params[:search]}%")
    elsif params[:item_type].present?
      @items = ItemDesign.where(item_type: params[:item_type]) 
    else
      @items = ItemDesign.all
    end
  end
end

app/views/item_designs/index.html.erb
<section class="section pb-5">

  <div class="">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
     <div class="search-box is-flex is-justify-content-center">
        <div class="search-text">
          <%= form_tag(item_designs_path, method: "get") do %>
          <%#= select_tag "search", options_from_collection_for_select(ItemDesign.all, :name, :name), class: 'select2'%>
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for an item" %>
        </div>
        <div class="search-icon is-flex">
          <%= button_tag(type: "submit", class: "btn-default") do %>
            <i class="fas fa-search fa-lg search-icon"></i>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

</section>

<section class="section pt-5">
  <div class="container">
    <h1 class="title is-uppercase has-text-weight-bold is-size-5">Items available</h1>
    <p><% @items.each do |item| %></p>
      <%= link_to item_design_path(item) do %>
        <div class="card px-2 pt-2 my-5 is-flex">
          <div class="card-image">
            <figure class="image image-item is-96x96 center">
              <%= image_tag "item_designs/#{item.item_type.downcase}s/#{item.name}.png" %>
            </figure>
          </div>
          <div class="card-content">
            <div class="card-content-title pb-2">
              <h2 class="has-text-weight-bold">
                <p><%= item.name %></p>
                <p><%= "#{item.refund_currency} #{item.refund_cents}" %></p>
              </h2>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</section>

app/views/item_designs/show.html.erb
<section class="section">
  <div class="card px-2 py-2 mt-5">
    <div class="card-header is-shadowless">
      <h3 class="card-header-title is-centered"><%= @item_design.name %></h3>
    </div>
    <div class="show-card px-3 pt-3 pb-5">
      <%= image_tag "item_designs/#{@item_design.item_type.downcase}s/#{@item_design.name}.png", class: "show-image" %>
    </div>
  </div>

  <div>
    <%= simple_form_for @secured_item do |f| %>
      <div class="card px-2 py-2 mb-5">
        <div class="subscriptions">
          <%= f.input_field :subscription_ids, as: :check_boxes,
           :collection => @subscriptions,
           :label_method => lambda { |subscription|
              "<div class=\"subscription-infos\">
                <h3>#{subscription.subscription_type}</h3>
                <h3 price-data=\"#{subscription.price}\">#{subscription.price.format}</h3><br>
              </div>".html_safe
            },
           label: false,
           include_hidden: false,
           class: "switch is-info is-rtl" %>
        </div>
        <div>
          Total: $
          <strong id="total">
          </strong> (per day)
        </div>
      </div>

      <%= f.hidden_field :item_design_id, value: @item_design.id %>
      <div class="card px-2 py-2 mb-5">

        <%= f.input :use_date, as: :boolean,
            :label => "   (Optional) Select start/end date for your insurance.", class: "switch is-info is-rtl" %>

        <div class="px-2 py-2">
          <%= f.input :activation_date, as: :date, :label => "Start Date",
              start_year: Date.today.year,
              end_year: Date.today.year %>
        </div>
        <div class="px-2 py-2">
          <%= f.input :expiration_date, as: :date, :label => "End Date",
              start_year: Date.today.year,
              end_year: Date.today.year %>
        </div>
      </div>
      <div class="has-text-centered">
        <%= f.button :submit, "Insure this item", class: "button is-dark" %>
      </div>
    <% end %>
  </div>

</section>