config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  root to: 'pages#home'
  resources :chatrooms, only: [:index, :show, :create] do
    resources :messages, only: :create
  end
  resources :item_designs, only: [:show, :index]
  resources :secured_items, only: [:new, :edit, :create, :update]
  get 'search', to: 'item_designs#index', as: :search
  get 'profile', to: 'pages#profile'
  patch 'secured_items/:id/activate', to: 'secured_items#activate', as: :activate
  patch 'secured_items/:id/deactivate', to: 'secured_items#deactivate', as: :deactivate
end

app/views/shared/_bottom_navbar.html.erb
<div class="d-block is-hidden-tablet">
  <div>
    <nav class="nav-bar-container" aria-hidden="false">
      <div class="nav-bar-content">
        <% if current_page?(root_path) %>
          <a class="nav-icon-container" href="/">
            <div class="nav-icon-content">
              <i class="fas fa-home fa-lg nav-icon"></i>
            </div>
            <div class="nav-icon-text nav-icon-text-select">Home</div>
          </a>
        <% else %>
          <a class="nav-icon-container" href="/">
            <div class="nav-icon-content">
              <i class="fas fa-home fa-lg"></i>
            </div>
            <div class="nav-icon-text">Home</div>
          </a>
        <% end %>

        <% if current_page?(search_path) %>
          <a class="nav-icon-container" href="/search">
            <div class="nav-icon-content">
              <i class="fas fa-search fa-lg nav-icon"></i>
            </div>
            <div class="nav-icon-text nav-icon-text-select">Search</div>
          </a>
        <% else %>
          <a class="nav-icon-container" href="/search">
            <div class="nav-icon-content">
              <i class="fas fa-search fa-lg"></i>
            </div>
            <div class="nav-icon-text">Search</div>
          </a>
        <% end %>

        <% if @chatroom %>
          <% if current_page?(chatroom_path(@chatroom)) %>
            <%= link_to(chatrooms_path, method: :post, class: "nav-icon-container") do %>
              <div class="nav-icon-content">
                <i class="fas fa-comment-alt fa-lg nav-icon"></i>
              </div>
              <div class="nav-icon-text nav-icon-text-select">Support</div>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to(chatrooms_path, method: :post, class: "nav-icon-container") do %>
            <div class="nav-icon-content">
              <i class="fas fa-comment-alt fa-lg"></i>
            </div>
            <div class="nav-icon-text">Support</div>
          <% end %>
        <% end %>


        <% if current_page?(profile_path) %>
          <a class="nav-icon-container" href="/profile">
            <div class="nav-icon-content">
              <i class="fas fa-user-circle fa-lg nav-icon"></i>
            </div>
            <div class="nav-icon-text nav-icon-text-select">Profile</div>
          </a>
        <% else %>
          <a class="nav-icon-container" href="/profile">
            <div class="nav-icon-content">
              <i class="fas fa-user-circle fa-lg"></i>
            </div>
            <div class="nav-icon-text">Profile</div>
          </a>
        <% end %>

      </div>
    </nav>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="notification is-success is-light" role="alert">
    <button type="button" class="delete" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="notification is-warning is-light" role="alert">
    <button type="button" class="delete" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div>
  <div>
    <nav class="nav-bar-container" aria-hidden="false">
      <div class="nav-bar-content">

        <a class="nav-icon-container" href="/">
          <div class="nav-icon-content">
            <svg viewBox="0 0 32 32"
              xmlns="http://www.w3.org/2000/svg"
              role="presentation"
              focusable="false"
              style="display: block; height: 24px; width: 24px; fill: currentcolor;">
              <path d="M23 3c2.106801 0 4.1361668.82306574 5.6571068 2.34289322 1.5202187 1.52021874 2.3428932 3.54936205 2.3428932 5.65710678 0 6.1258166-4.1336896 10.7413484-13.2771622 17.0360378l-.4613525.3161485-1.2603024.8557461-.561306-.379523c-10.08413946-6.8183189-14.4398769-11.4368525-14.4398769-17.8284094 0-2.1072166.82336538-4.13657894 2.34389322-5.65710678 1.51945266-1.51945266 3.54974264-2.34289322 5.65610678-2.34289322 2.0014609 0 3.9330366.74281683 5.4253543 2.12030845l.2319249.22275721 1.3417208 1.34293434 1.3448932-1.34310678c1.3675074-1.36750739 3.148793-2.17124499 5.0269145-2.31831743l.3138626-.01841591zm0 2c-1.4881441 0-2.9222843.54615204-4.0367433 1.5612911l-.2051499.19581568-2.7582792 2.75827923-2.7566756-2.75802055c-1.1419182-1.14108286-2.6614358-1.75736546-4.243152-1.75736546-1.58115306 0-3.10134088.61655445-4.24189322 1.75710678-1.14169457 1.14169457-1.75810678 2.660976-1.75810678 4.24289322 0 5.1012962 3.53044809 9.1738639 11.7845794 14.9510839l.8707748.6038363.3446458.2350798.5857119-.3992616.8733618-.6071874c7.706855-5.4127073 11.2817846-9.4483722 11.5273066-14.2471091l.0102199-.2673951.0033998-.2690468c0-1.5826219-.6158555-3.1016419-1.756848-4.24263454-1.1419182-1.14108286-2.6614358-1.75736546-4.243152-1.75736546z"></path>
            </svg>
          </div>
          <div class="nav-icon-text">Home</div>
        </a>

        <a class="nav-icon-container" href="/index">
          <div class="nav-icon-content">
            <svg viewBox="0 0 32 32"
              xmlns="http://www.w3.org/2000/svg"
              aria-hidden="true"
              role="presentation"
              focusable="false"
              style="display: block; fill: none; height: 24px; width: 24px; stroke: currentcolor; stroke-width: 4; overflow: visible;">
              <g fill="none">
                <path d="M13 24c6.0751322 0 11-4.9248678 11-11 0-6.07513225-4.9248678-11-11-11-6.07513225 0-11 4.92486775-11 11 0 6.0751322 4.92486775 11 11 11zm8-3 9 9"></path>
              </g>
            </svg>
          </div>
          <div class="nav-icon-text">Search</div>
        </a>

        <a class="nav-icon-container" href="/support">
          <div class="nav-icon-content">
            <svg viewBox="0 0 32 32"
              xmlns="http://www.w3.org/2000/svg"
              aria-hidden="true"
              role="presentation"
              focusable="false"
              style="display: block; height: 24px; width: 24px; fill: currentcolor;">
              <path d="M26 2c2.6887547 0 4.8818181 2.12230671 4.9953805 4.78311038l.0046195.21688962v14c0 2.6887547-2.1223067 4.8818181-4.7831104 4.9953805l-.2168896.0046195h-5.845l-4.1548949 5.0792674-4.1561051-5.0792674h-5.844c-2.61406707 0-4.75959878-2.0060384-4.98113724-4.5626572l-.01424325-.2204532-.00461951-.2168896v-14c0-2.6887547 2.12230671-4.88181811 4.78311038-4.99538049l.21688962-.00461951zm0 2h-20c-1.59768088 0-2.90366088 1.24891996-2.99490731 2.82372721l-.00509269.17627279v14c0 1.5976809 1.24891996 2.9036609 2.82372721 2.9949073l.17627279.0050927h6.7918643l3.2071357 3.92 3.2080542-3.92h6.7929458c1.5976809 0 2.9036609-1.24892 2.9949073-2.8237272l.0050927-.1762728v-14c0-1.59768088-1.24892-2.90366088-2.8237272-2.99490731z"></path>
            </svg>
          </div>
          <div class="nav-icon-text">Support</div>
        </a>

        <a class="nav-icon-container" href="/profile">
          <div class="nav-icon-content">
            <svg viewBox="0 0 32 32"
              xmlns="http://www.w3.org/2000/svg"
              aria-hidden="true"
              role="presentation"
              focusable="false"
              style="display: block; height: 24px; width: 24px; fill: currentcolor;">
              <path d="M16 1c8.2842712 0 15 6.71572875 15 15 0 8.2842712-6.7157288 15-15 15-8.28427125 0-15-6.7157288-15-15 0-8.28427125 6.71572875-15 15-15zm0 8c-2.7614237 0-5 2.2385763-5 5 0 2.0143973 1.2022141 3.7998876 2.9996346 4.5835001l.0003231 2.0984999-.1499943.0278452c-2.8326474.5613112-5.31897338 2.2230336-6.93575953 4.5872979 2.34343054 2.291067 5.54974273 3.7028569 9.08579613 3.7028569 3.5355506 0 6.7414538-1.4113884 9.0850203-3.701476-1.6141801-2.3628535-4.0978119-4.0247647-6.929184-4.5867938l-.1558786-.0287302.001228-2.0991413c1.7288399-.7547474 2.9066959-2.4357565 2.9936498-4.355479l.0051645-.2283797c0-2.7614237-2.2385763-5-5-5zm0-6c-7.17970175 0-13 5.82029825-13 13 0 2.9045768.95257276 5.5866683 2.56235849 7.7509147 1.42074739-1.9134907 3.33951478-3.4002416 5.53860831-4.2955956l.3480332-.1363191-.0229565-.0189706c-1.43704227-1.2411241-2.34462949-3.045583-2.42083359-5.0285539l-.00520991-.2714755c0-3.8659932 3.1340068-7 7-7s7 3.1340068 7 7c0 1.9941317-.8415062 3.8279876-2.224566 5.1193683l-.225434.2006317.0447787.0163138c2.3268368.8792152 4.3570558 2.4138611 5.8430586 4.4127726 1.6098837-2.1632453 2.5621627-4.8449575 2.5621627-7.7490864 0-7.17970175-5.8202983-13-13-13z"></path>
            </svg>
          </div>
          <div class="nav-icon-text">Profile</div>
        </a>

      </div>
    </nav>
  </div>
</div>

app/views/shared/_top_navbar.html.erb
<nav class="navbar has-shadow py-1" role="navigation" aria-label="main navigation">
  <div class="navbar-brand px-5">
    <div class="navbar-item">
      <%= link_to root_path, class: "" do %>
        <%= image_tag "safely.jpg" %>
      <% end %>
    </div>
  </div>

  <div class="navbar-menu" id="navbarMenu" >
    <div class="navbar-start">
    </div>
    <div class="navbar-end">
    </div>
  </div>
</nav>