config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  root to: 'pages#home'
  resources :chatrooms, only: [:index, :show, :create] do
    resources :messages, only: :create
  end
  resources :item_designs, only: [:show, :index]
  resources :secured_items, only: [:new, :edit, :create, :update]
  get 'search', to: 'item_designs#index', as: :search
  get 'profile', to: 'pages#profile'
  patch 'secured_items/:id/activate', to: 'secured_items#activate', as: :activate
  patch 'secured_items/:id/deactivate', to: 'secured_items#deactivate', as: :deactivate
end

app/views/pages/home.html.erb
<section class="section pb-5">
  <div class="">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="search-box is-flex is-justify-content-center">
        <div class="search-text">
          <%= form_tag(item_designs_path, method: "get") do %>
          <%#= select_tag "search", options_from_collection_for_select(ItemDesign.all, :name, :name), class: 'select2'%>
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search for an item" %>
        </div>
        <div class="is-flex search-icon">
          <%= button_tag(type: "submit", class: "btn-default") do %>
            <i class="fas fa-search fa-lg search-icon"></i>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section class="section pt-0">
  <div class="container">
    <%= link_to item_designs_path(item_type: "Car") do %><br>
      <div class="card home-card-container px-2 py-2">
        <div class="is-flex home-card">
          <div class="home-icon">
            <i class="fas fa-car fa-3x"></i>
          </div>
          <div class="card-content home-card-content home-card-text">
            <div class="card-content-title">
              <h2 class="title is-uppercase has-text-weight-bold is-size-6 pt-2">
                <p>Cars</p>
               </h2>
            </div>
          </div>
        </div>

      </div>
    <% end %>
  </div>

  <div class="container">
    <%= link_to item_designs_path(item_type: "Phone") do %><br>
      <div class="card home-card-container px-2 py-2">
        <div class="is-flex home-card">
          <div class="home-icon">
            <i class="fas fa-mobile-alt fa-3x"></i>
          </div>
          <div class="card-content home-card-content home-card-text">
            <div class="card-content-title">
              <h2 class="title is-uppercase has-text-weight-bold is-size-6">
                <p>Mobiles</p>
               </h2>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>


  <div class="container">
    <%= link_to item_designs_path(item_type: "Notebook") do %><br>
      <div class="card home-card-container px-2 py-2">
        <div class="is-flex home-card">
          <div class="home-icon">
            <i class="fas fa-laptop fa-3x"></i>
          </div>
          <div class="card-content home-card-content home-card-text">
            <div class="card-content-title">
              <h2 class="title is-uppercase has-text-weight-bold is-size-6">
                <p>Notebooks</p>
               </h2>
            </div>
          </div>
        </div>

      </div>
    <% end %>
  </div>

  <% unless current_user %>
    <div class="level my-5">
      <%= link_to "Log In", new_user_session_path, method: :get, class: "button is-dark level-item has-text-centered" %>
    </div>

    <div class="level my-2">
      <%= link_to "Sign Up", new_user_registration_path, method: :get, class: "button is-dark level-item has-text-centered" %>
    </div>
  <% end %>

</section>

app/views/pages/profile.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <% if current_user %>
        <div class="level">
          <div class="card-image level-item has-text-centered">
            <figure class="image profile-image is-inline-block">
              <% if current_user.photo %>
                <%= image_tag "leticia_kanegae.png", :class => "image is-rounded" %>
              <% else %>
                <img class="image is-rounded" src="https://bulma.io/images/placeholders/256x256.png">
              <% end %>
            </figure>
          </div>
          <div class="container">
            <h3 class="has-text-centered is-size-4">
              <%= current_user.first_name %> <%= current_user.last_name %>
            </h3>
          </div>
          <div class="container mt-6">
            <h1 class="title mb-4 is-uppercase has-text-weight-bold is-size-5">Personal Info</h1>
            <p class="is-size-6">Name: <%= current_user.first_name %> <%= current_user.last_name %></p>
            <p class="is-size-6">Address: <%= current_user.address %></p>
            <p class="is-size-6">Phone Number: <%= current_user.phone_number %></p>
            <p class="is-size-6">Birth Date: <%= current_user.birth_date %></p>
          </div>
          <div class="mt-4">
            <%= link_to "Edit", edit_user_registration_path, method: "get", class: "button is-dark level-item has-text-centered" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <h1 class="title is-uppercase has-text-weight-bold is-size-5">My Items</h1>
  </div>

  <div class="container mt-4">
    <h2 class="subtitle">Activate Insurance</h2>
    <% if @activate.any? %>
      <div>
        <% @activate.reverse_each do |user_item| %>
          <div class="card px-2 py-2 my-5" id="user_item-<%= user_item.id %>">
            <div class="is-flex">
              <div class="card-image">
                <figure class="image image-item is-96x96 center">
                  <%= image_tag "item_designs/#{user_item.item_design.item_type.downcase}s/#{user_item.item_design.name}.png" %>
                </figure>
              </div>
              <div class="card-content pt-3">
                <div class="card-content-title pb-2">
                  <h2 class="has-text-weight-bold">
                    <%= user_item.item_design.name %>
                  </h2>
                </div>
                <div class="card-content-options">
                  <div class="is-flex is-justify-content-space-between">
                    <% if user_item.activation_date.nil? %>
                      <div>
                        <%= button_to "Activate", activate_path(user_item),
                          method: :patch, data: { confirm: "Please confirm the insurance activation." },
                          class: "button is-dark is-small",
                          remote: true %>
                      </div>
                    <% else %>
                      <div>
                        <%= button_to "Deactivate", deactivate_path(user_item),
                          method: :patch, data: { confirm: "Please confirm the insurance deactivation." },
                          class: "button is-dark is-small",
                          remote: true %>
                      </div>
                    <% end %>
                    <div class="ml-3">
                      <%=  link_to "Edit", edit_secured_item_path(user_item), method: "get", class: "button is-dark is-small" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="my-5">
        <h1>You still don't have any insurance options</h1>
        <%= button_to "Insure an item", item_designs_path, method: 'get' %>
      </div>
    <% end %>
  </div>

  <div class="container mt-4">
    <h2 class="subtitle">Currently Insured</h2>
    <% if @currently.any? %>
      <div>
        <% @currently.reverse_each do |user_item| %>
          <div class="card px-2 py-2 my-5" id="user_item-<%= user_item.id %>">
            <div class="is-flex">
              <div class="card-image">
                <figure class="image is-96x96">
                  <%= image_tag "item_designs/#{user_item.item_design.item_type.downcase}s/#{user_item.item_design.name}.png" %>
                </figure>
              </div>
              <div class="card-content pt-3">
                <div class="card-content-title pb-2">
                  <h2 class="has-text-weight-bold">
                    <%= user_item.item_design.name %>
                  </h2>
                  <p class="is-size-7">
                    <%= user_item.activation_date %> || <%= user_item.expiration_date %>
                  </p>
                </div>
                <div class="card-content-options">
                  <div class="is-flex is-justify-content-space-between">
                  <% if user_item.use_date == false %>
                    <div>
                      <%= button_to "Deactivate", deactivate_path(user_item),
                        method: :patch, data: { confirm: "Please confirm the insurance deactivation." },
                        class: "button is-dark is-small",
                        remote: true %>
                    </div>
                  <% end %>
                      <div class="ml-3">
                      <%=  link_to "Edit", edit_secured_item_path(user_item), method: "get", class: "button is-dark is-small" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="my-5">
        <h1>No insurances to activate</h1>
      </div>
    <% end %>
  </div>

  <div class="container mt-4">
    <% if @item_designs.any? %>
      <h2 class="subtitle">Insure again</h2>
      <% @item_designs.each do |expired_item| %>
        <div class="card px-2 pt-2 my-5 is-flex" id="expired_item-<%= expired_item.id %>">
          <div class="card-image">
            <figure class="image is-96x96">
              <%= image_tag "item_designs/#{expired_item.item_type.downcase}s/#{expired_item.name}.png" %>
            </figure>
          </div>
          <div class="card-content">
            <div class="card-content-title pb-2">
              <h2 class="has-text-weight-bold">
                <%= expired_item.name %>
              </h2>
            </div>
            <%= button_to "New Insurance", item_design_path(expired_item), method: :get, class: "button is-dark is-small" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</section>

<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class= "title is-uppercase has-text-weight-bold is-size-5">December's total expenses</h1>
    </div>

    <div class="container mt-4">
      <% if current_user %>
        <div class="level">
          <div class="container">
            <% if @expired %>
              <p class="is-size-6">
                <% @expired.each do |item| %>
                  <%= item.item_design.name + " - " + humanized_money_with_symbol(item.total_price) %>
                  <br>
                <% end  %>
              <p class="is-size-6"><b>Total:</b> <%= calculate_total_price(@expired) %></p>
              </div>
            <% else %>
              <p class="is-size-6">Billing: $0,00</p>
            <% end %>
          </div>

          <div class="container">
            <h1 class="title is-uppercase has-text-weight-bold is-size-5 mt-6">Billing Information</h1>
            <p>CARD 1: MASTERCARD</p>
            <p>Credit Card: **** **** **** 1256</p>
            <p>Expiration Date: 10/29</p>

            <p class="mt-4">CARD 2: VISA</p>
            <p>Credit Card: **** **** **** 2765</p>
            <p>Expiration Date: 10/27</p>
          </div>

          <div class="mt-4">
            <%= link_to "Edit", edit_user_registration_path, method: "get", class: "button is-dark level-item has-text-centered" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

<section class="hero is-light mb-6">
  <div class="hero-body">
    <div class="level">
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "button is-light level-item has-text-centered has-text-weight-bold" %>
    </div>
  </div>

</section>